name: Tests

on:
  push:
    branches:
      - 'main'

  pull_request:
    types: [ opened, reopened, synchronize, labeled ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Ensure latest pip
        run: python -m pip install --upgrade pip

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --all-extras --all-groups

      - name: Run tests
        run: uv run pytest -ra -q --dist=loadscope --cov=hgraph --cov-report=xml